=== jesterswilde/RootAccess/Assets/GameData/Forum/forumSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["threadTitle", "id", "priority", "posts"],
    "properties": {
        "id": {
            "type": "string"
        },
        "conditions":{
            "type": "array",
            "items":{
                "$ref": "../requiremntsSchema.json"
            }
        },
        "priority": {
            "type": "integer"
        },
        "threadTitle":{
            "type": "string"
        },
        "createdBy":{
            "type": "string",
            "$ref": "./usernameSchema.json"
        },
        "posts":{
            "type":"array",
            "items": {
                "$ref": "./postSchema.json"
            }
        }
    }
}

=== jesterswilde/RootAccess/Assets/GameData/Forum/Threads/conditionalIntroduction.json
{
    "createdBy": "anthrax",
    "priority": 1,
    "threadTitle": "Introductions",
    "id": "anthraxDoesnotLikeYou",
    "conditions": [
        {
            "condition": "Rep", "user": "anthrax", "rep": 0, "op": "<"
        },
        {
            "condition": "Flag", "flag": "completedObservatory","value": 1,"op": "=="
        }
    ],
    "posts": [
        {
            "title": "Introductions",
            "content": "I'm anthrax, and I don't like you. I'm here to make sure you don't get too comfortable. I'm watching you."
        }]
}
